### ISSUE TITLE
Create MVP home page with functional navbar

### ISSUE THREAD

**Issue by muscarellaanthony** [muscarellaanthony/AquatiCATS#3]

**Comment by 404pandas** [comment]
<img width="949" alt="Screenshot 2024-07-26 at 10 03 59 PM" src="https://github.com/user-attachments/assets/dc4fd331-06f7-461b-a800-1ede36d9c31b">
Wireframe provided by @muscarellaanthony 
https://www.figma.com/design/CIOedpiPmchVBSYrwP9AXa/AquatiCATS?node-id=0-1
